# Concevez et déployez un système RAG

## Objectif de ce notebook : nettoyage de nos données afin d'effectuer les vecteurs
#### Description
Récupérer les données d'événements à partir de la plateforme Open Agenda, les filtrer par localisation et période, et structurer ces données pour une utilisation future dans la base de données vectorielle.
#### Résultat attendu
Un jeu de données d'événements propre et structuré, prêt à être indexé. Vous pourrez effectuer des tests unitaires pour vous assurer d’avoir récupérer les données attendues.
#### Recommandations
- Utiliser l'API Open Agenda pour récupérer les événements.
- Filtrer les événements par localisation et période (1 an d'historique et événements à venir).
- Convertir les descriptions des événements en format vectoriel avec un modèle de NLP comme Mistral.

## Librairies nécessaires

In [1]:
# Imports standards
import faiss
import requests
import pandas as pd
import numpy as np

# Imports LangChain
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings # ou SentenceTransformerEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from sentence_transformers import SentenceTransformer


# Import Mistral
from mistralai.client import MistralClient

import os
from dotenv import load_dotenv
from mistralai import Mistral

/Users/florianschorer/Library/Caches/pypoetry/virtualenvs/deploiement-systeme-rag-2X291xtv-py3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Récupération des données via l'API d'Open Agenda
Nou avons fait le choix de prendre la ville de Paris pour ce POC. L'objectif est de pouvoir montrer que le poc fonctionne pour une grande ville et pourra être généralisable à plusieurs villes puis plusieurs pays etc.

Paris est un choix raisonné car c'est une ville avec beaucoup d'évènements culturels.
Dans un premier temps nous allons nous focaliser sur 100 lignes afin de contrôler la cohérence de nos éléments.
Pour le filtre de temps, nous prenons la variable "lastdate_end" afin d'avoir les bonnes dates de fin d'un événement.
Nous fixons la temporalité entre le 01/01/2025 et 01/01/2027 pour obtenir l'historique des informations sur 1 an + les informations sur l'année 2026 à venir.

#### Récupérons des informations depuis l'API, 100 lignes pour le moment.

In [2]:
# Chemin pour l'API d'Open Agenda sur le dataset des évènements publics
url = "https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/evenements-publics-openagenda/records"

params = {
    "limit": 100,
    "lang": "fr",
    # Choix de la localisation à Paris
    "refine": ["location_city:Paris"],
    "where": (
        # lastdate_end = dernière date à laquelle se termine l’évènement
        # Choix de prendre des évènements qui finissent après le 01/01/2025
        "lastdate_end >= '2025-01-01' "
        # Prendre les évènements en  compte jusqu'avril 2026
        "AND lastdate_end <= '2026-04-01'"
    ),
    # Classé par ordre décroissant afin d'avoir des données en 2025 et 2026
    "order_by": "lastdate_end desc"
}

response = requests.get(url, params=params)
response.raise_for_status()
data = response.json()

df = pd.DataFrame(data.get("results"))
df.head()

,uid,slug,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,keywords_fr,image,imagecredits,...,originagenda_uid,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category,country_fr,registration,links
0,66000118,kohlhaas-4508066,https://openagenda.com/culture/events/kohlhaas...,Kohlhaas,estrarre - Julien Kosellek,"<p>À la frontière du théâtre et du conte, Kohl...",Entrée libre sur réservation pour les experts ...,"[Récit, Narration, von Kleist, Révolte, injust...",https://cdn.openagenda.com/main/418694f0481849...,© Paola Valentin,...,97606842,None,None,None,None,None,None,France (Métropole),"[{""type"": ""email"", ""value"": ""production@estrar...","[{""link"": ""http://estrarre.fr""}, {""data"": {""au..."
1,80142793,representation-moi-elles,https://openagenda.com/culture/events/represen...,"Représentation - Moi, Elles",Cie Abricotier d'Argent - Jing WANG,"<p><em>Moi, Elles</em> est une pièce de théâtr...",Sur inscription,None,https://cdn.openagenda.com/main/abf7143914cf4c...,None,...,97606842,None,None,None,None,None,None,France (Métropole),"[{""type"": ""email"", ""value"": ""hybriditesfrancec...",None
2,63232931,ascanio-in-alba-mozart,https://openagenda.com/culture/events/ascanio-...,"LES TALENS LYRIQUES - Ascanio in Alba, Mozart",Christophe Rousset,<p>Festa teatrale en deux actes à Milan au Reg...,None,None,https://cdn.openagenda.com/main/279a69ad076d47...,None,...,73237661,None,None,None,None,None,None,France (Métropole),"[{""type"": ""link"", ""value"": ""https://25-26.thea...",None
3,5148482,les-lundis-musicaux-contes,https://openagenda.com/culture/events/les-lund...,LE BALCON : LES LUNDIS MUSICAUX - Contes,Après avoir enflammé les planches de l’Athénée...,<p>Après avoir enflammé les planches de l’Athé...,12 à 30€,"[Les Lundis Musicaux, Sandrine Piau, David Kad...",https://cdn.openagenda.com/main/47d78f825f3f4f...,Lilli Lacombe,...,73237661,None,None,None,None,None,None,France (Métropole),"[{""type"": ""link"", ""value"": ""https://athenee-th...",None
4,1617629,maison-de-poupee-6574989,https://openagenda.com/culture/events/maison-d...,Maison de Poupée,Plexus Polaire / Yngvild Aspeli,<p>“Tout a commencé par le bruit d’un oiseau q...,None,"[yngvild, aspeli, polaire, maison, poupée, ara...",https://cdn.openagenda.com/main/845e82035a0349...,None,...,76685088,None,None,None,None,None,None,France (Métropole),None,None

- Nous avons bien un dataframe avec des évènements,  ce qu'il se passe d'un peu plus près.

In [22]:
pd.set_option('display.max_colwidth', None)
print(df[['uid','title_fr','description_fr','description_fr','conditions_fr','firstdate_begin','lastdate_end']].iloc[72])

uid                                                                                                                                      1641036
title_fr                                                                                                           LES CRIS DE PARIS - Balliamo!
description_fr     Production Les Cris de Paris Coproduction Centre de Culture et de Rencontres d’Ambronay, Théâtre de Saint-Quentin-en-Yvelines
description_fr     Production Les Cris de Paris Coproduction Centre de Culture et de Rencontres d’Ambronay, Théâtre de Saint-Quentin-en-Yvelines
conditions_fr             https://www.maisondelaradioetdelamusique.fr/evenement/madrigaux-de-monteverdi-les-cris-de-paris?s=1081206#content-page
firstdate_begin                                                                                                        2025-12-16T19:00:00+00:00
lastdate_end                                                                                                           2025-12-16T21:00:00+00:00
Name: 72, dtype: object

#### Sur les 100 lignes extraites on a décidé de les filtrer par ordre décroissant afin d'obtenir des éléments de 2026 également. Pour obtenir une meilleure représentation d'une année d'historique, il faudra augmenter le nombre de lignes.

In [3]:
print(df['lastdate_end'].str[:7].value_counts())
df['lastdate_end'].str[:4].value_counts()

lastdate_end
2025-11    22
2026-02    21
2026-01    21
2025-12    20
2026-03    15
2026-04     1
Name: count, dtype: int64

lastdate_end
2026    58
2025    42
Name: count, dtype: int64

- On obtient un petit équilibre entre les deux années, pour le moment cela nous convient.

### Regardons d'un peu plus près notre dataframe
#### On va déjà regarder si le nombre de lignes correspond bien à ce que l'on voulait

In [4]:
df_shape = df.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.

#### Regardons les colonnes que nous avons. Nous pourrons décider déjà d'un point de vu métier ce qui nous paraît intéressant.

In [5]:
df.columns

Index(['uid', 'slug', 'canonicalurl', 'title_fr', 'description_fr',
       'longdescription_fr', 'conditions_fr', 'keywords_fr', 'image',
       'imagecredits', 'thumbnail', 'originalimage', 'updatedat',
       'daterange_fr', 'firstdate_begin', 'firstdate_end', 'lastdate_begin',
       'lastdate_end', 'timings', 'accessibility', 'accessibility_label_fr',
       'location_uid', 'location_coordinates', 'location_name',
       'location_address', 'location_district', 'location_insee',
       'location_postalcode', 'location_city', 'location_department',
       'location_region', 'location_countrycode', 'location_image',
       'location_imagecredits', 'location_phone', 'location_website',
       'location_links', 'location_tags', 'location_description_fr',
       'location_access_fr', 'attendancemode', 'onlineaccesslink', 'status',
       'age_min', 'age_max', 'originagenda_title', 'originagenda_uid',
       'contributor_email', 'contributor_contactnumber',
       'contributor_contactname', 'contributor_contactposition',
       'contributor_organization', 'category', 'country_fr', 'registration',
       'links'],
      dtype='object')

- **Les éléments non indispensables d'un point de vu métier** : 
    - "image", "imagecredits","thumbnail","originalimage","accessibility"
    - "location_coordinates", "location_city","location_insee","location_department"
    - "location_region","location_countrycode","location_image","location_imagecredits","location_tags"
    - "attendancemode", "onlineaccesslink","country_fr","registration","links","originagenda_uid"
    - Intéressant de garder qu'une date qui comprend la date de début et de de fin ainsi que la date que nous avons sélectionné / Nous traiterons avec plus d'attention les dates lorsque nous préparerons les métadonnées

#### Colonnes à enlever du point de vu métier.

In [6]:
col_business_side = [
    "image", "imagecredits","thumbnail","originalimage","accessibility", "location_uid",
    "location_coordinates", "location_city","location_insee","location_department",
    "location_region","location_countrycode","location_image","location_imagecredits","location_tags",
    "attendancemode", "onlineaccesslink","country_fr","registration","links","originagenda_uid"
    ]
len(col_business_side)

21

* Identification de 21 colonnes non pertinentes pour notre projet d'un point de vu métier

#### Examinons les différentes dates possibles

In [7]:
df[["updatedat","daterange_fr","firstdate_begin","firstdate_end","lastdate_begin","lastdate_end","timings"]]

,updatedat,daterange_fr,firstdate_begin,firstdate_end,lastdate_begin,lastdate_end,timings
0,2025-09-24T08:48:05+00:00,24 mars - 1 avril 2026,2026-03-24T13:30:00+00:00,2026-03-24T14:30:00+00:00,2026-04-01T08:00:00+00:00,2026-04-01T09:00:00+00:00,"[{""begin"": ""2026-03-24T14:30:00+01:00"", ""end"":..."
1,2025-10-29T14:03:41+00:00,19 - 28 mars 2026,2026-03-19T18:30:00+00:00,2026-03-19T20:10:00+00:00,2026-03-28T17:00:00+00:00,2026-03-28T18:40:00+00:00,"[{""begin"": ""2026-03-19T19:30:00+01:00"", ""end"":..."
2,2025-06-25T15:52:36+00:00,"Mercredi 25 mars 2026, 19h30",2026-03-25T18:30:00+00:00,2026-03-25T21:00:00+00:00,2026-03-25T18:30:00+00:00,2026-03-25T21:00:00+00:00,"[{""begin"": ""2026-03-25T19:30:00+01:00"", ""end"":..."
3,2025-09-01T15:38:05+00:00,"Lundi 23 mars 2026, 20h00",2026-03-23T19:00:00+00:00,2026-03-23T20:30:00+00:00,2026-03-23T19:00:00+00:00,2026-03-23T20:30:00+00:00,"[{""begin"": ""2026-03-23T20:00:00+01:00"", ""end"":..."
4,2025-06-25T15:53:20+00:00,17 - 22 mars 2026,2026-03-17T19:00:00+00:00,2026-03-17T20:30:00+00:00,2026-03-22T19:00:00+00:00,2026-03-22T20:30:00+00:00,"[{""begin"": ""2026-03-17T20:00:00+01:00"", ""end"":..."
...,...,...,...,...,...,...,...
95,2025-10-30T09:39:21+00:00,"Jeudi 27 novembre, 20h00",2025-11-27T19:00:00+00:00,2025-11-27T22:00:00+00:00,2025-11-27T19:00:00+00:00,2025-11-27T22:00:00+00:00,"[{""begin"": ""2025-11-27T20:00:00+01:00"", ""end"":..."
96,2025-08-20T10:03:03+00:00,"Jeudi 27 novembre, 19h30, 21h30",2025-11-27T18:30:00+00:00,2025-11-27T19:30:00+00:00,2025-11-27T20:30:00+00:00,2025-11-27T21:30:00+00:00,"[{""begin"": ""2025-11-27T19:30:00+01:00"", ""end"":..."
97,2025-10-07T14:37:33+00:00,"Jeudi 27 novembre, 20h00",2025-11-27T19:00:00+00:00,2025-11-27T20:45:00+00:00,2025-11-27T19:00:00+00:00,2025-11-27T20:45:00+00:00,"[{""begin"": ""2025-11-27T20:00:00+01:00"", ""end"":..."
98,2025-07-29T13:35:21+00:00,22 - 27 novembre,2025-11-22T17:30:00+00:00,2025-11-22T19:40:00+00:00,2025-11-27T18:30:00+00:00,2025-11-27T20:40:00+00:00,"[{""begin"": ""2025-11-22T18:30:00+01:00"", ""end"":..."
99,2025-10-29T08:18:07+00:00,"Jeudi 27 novembre 2025, 09h30",2025-11-27T08:30:00+00:00,2025-11-27T11:30:00+00:00,2025-11-27T08:30:00+00:00,2025-11-27T11:30:00+00:00,"[{""begin"": ""2025-11-27T09:30:00+01:00"", ""end"":..."

* Difficile d'évaluer laquelle des colonnes est la plus pertinente pour le moment. A voir lorsque nous verrons avec les métadonnées.

#### Supprimons de notre dataframe les colonnes inutiles pour le moment.

In [8]:
df_test_clean = df.drop(columns=col_business_side)

In [9]:
df_test_clean_shape = df_test_clean.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")
print(f"Nous avons {df_test_clean_shape[0]} lignes et {df_test_clean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu métier.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.
Nous avons 100 lignes et 35 colonnes après suppression des colonnes inutiles du point de vu métier.

#### Regardons par identifiant si nous remarquons des doublons

In [10]:
df_test_clean["uid"]

0     66000118
1     80142793
2     63232931
3      5148482
4      1617629
        ...
95    33103396
96    25322273
97    10147870
98    41991358
99    67704765
Name: uid, Length: 100, dtype: object

In [11]:
df_test_clean["uid"].duplicated().any()

np.False_

* Pas de doublons par identifiant

#### Regardons le nombre de valeurs manquantes par variable 
#### L'objectif va être de sélectionner les colonnes inutiles d'un point de vu data cette fois.

In [12]:
df_test_clean.isnull().mean()

uid                            0.00
slug                           0.00
canonicalurl                   0.00
title_fr                       0.00
description_fr                 0.00
longdescription_fr             0.02
conditions_fr                  0.49
keywords_fr                    0.17
updatedat                      0.00
daterange_fr                   0.00
firstdate_begin                0.00
firstdate_end                  0.00
lastdate_begin                 0.00
lastdate_end                   0.00
timings                        0.00
accessibility_label_fr         0.77
location_name                  0.00
location_address               0.00
location_district              0.18
location_postalcode            0.00
location_phone                 0.93
location_website               0.91
location_links                 0.83
location_description_fr        0.79
location_access_fr             0.91
status                         0.00
age_min                        0.80
age_max                        0.60
originagenda_title             0.00
contributor_email              1.00
contributor_contactnumber      1.00
contributor_contactname        1.00
contributor_contactposition    1.00
contributor_organization       1.00
category                       1.00
dtype: float64

#### Filtrons sur les variables avec plus de 70% de valeurs manquantes afin de voir si les variables sont importantes ou non.

In [13]:
df_missed_values = df_test_clean.loc[:, df_test_clean.isnull().mean()>=0.70]
df_missed_values.isnull().mean()

accessibility_label_fr         0.77
location_phone                 0.93
location_website               0.91
location_links                 0.83
location_description_fr        0.79
location_access_fr             0.91
age_min                        0.80
contributor_email              1.00
contributor_contactnumber      1.00
contributor_contactname        1.00
contributor_contactposition    1.00
contributor_organization       1.00
category                       1.00
dtype: float64

#### Regardons à quoi ressemble ces données

In [14]:
df_missed_values

,accessibility_label_fr,location_phone,location_website,location_links,location_description_fr,location_access_fr,age_min,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category
0,None,None,None,None,None,None,10.0,None,None,None,None,None,None
1,None,None,None,None,None,None,14.0,None,None,None,None,None,None
2,None,None,None,None,None,None,NaN,None,None,None,None,None,None
3,None,None,None,None,None,None,NaN,None,None,None,None,None,None
4,None,None,None,None,None,None,14.0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,None,None,https://nouveaucasino.fr/,https://www.facebook.com/nouveaucasinoparis/?l...,Club et salle de concert depuis 1999.\nLieu my...,None,NaN,None,None,None,None,None,None
96,None,None,None,None,None,None,NaN,None,None,None,None,None,None
97,None,None,None,https://www.facebook.com/profile.php?id=615559...,"Bar inclusif.\nKaraoke, DJ set, Cabaret, Expo",None,NaN,None,None,None,None,None,None
98,"[handicap auditif, handicap visuel]",None,None,None,None,None,NaN,None,None,None,None,None,None
99,None,None,None,None,None,None,NaN,None,None,None,None,None,None

* Au vu du nombre des données manquantes et la non-utilité pour notre chatbot (pas d'éléments concernant réellement un évènement particulier) on peut supprimer ces colonnes.
* On décide de garder l'âge minimum pour le moment car cela peut être une variable intéressante par la suite

In [15]:
df_missed_values = df_test_clean.loc[
    :,
    (df_test_clean.isnull().mean() >= 0.70)
    & (df_test_clean.columns != "age_min")
]

In [16]:
df_missed_values.columns

Index(['accessibility_label_fr', 'location_phone', 'location_website',
       'location_links', 'location_description_fr', 'location_access_fr',
       'contributor_email', 'contributor_contactnumber',
       'contributor_contactname', 'contributor_contactposition',
       'contributor_organization', 'category'],
      dtype='object')

In [17]:
df_col_missed = df_missed_values.columns
print(f"On peut supprimer ces {len(df_col_missed)} colonnes.")

On peut supprimer ces 12 colonnes.

#### Suppression des colonnes manquantes

In [18]:
df_firstclean = df_test_clean.drop(columns=df_col_missed)

In [19]:
df_firstclean_shape = df_firstclean.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")
print(f"Nous avons {df_test_clean_shape[0]} lignes et {df_test_clean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu métier.")
print(f"Nous avons {df_firstclean_shape[0]} lignes et {df_firstclean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu data.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.
Nous avons 100 lignes et 35 colonnes après suppression des colonnes inutiles du point de vu métier.
Nous avons 100 lignes et 23 colonnes après suppression des colonnes inutiles du point de vu data.